# Generated by Django 4.1.2 on 2022-10-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('nombreCompleto', models.CharField(max_length=200)),
                ('Contrasena', models.CharField(max_length=200)),
                ('PreguntaSecreta', models.IntegerField()),
                ('Respuesta', models.TextField()),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.CharField(max_length=150)),
                ('FechaRegistro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
