# Generated by Django 4.1.1 on 2022-10-24 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Universidad', '0002_persona_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.TextField(max_length=100)),
                ('Slug', models.SlugField()),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('UsuarioCreacion', models.TextField()),
                ('Contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('UsuarioCreacion', models.CharField(max_length=30)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Universidad.post')),
            ],
        ),
    ]
